<?php

Class Helper{ 
    

    public static function colourOption(){
      $colour ='
<option value="#0048BA_Absolute Zero">Absolute Zero</option>
<option value="#B0BF1A_Acid green">Acid green</option>
<option value="#7CB9E8_Aero">Aero</option>
<option value="#C0E8D5_Aero blue">Aero blue</option>
<option value="#B284BE_African violet">African violet</option>
<option value="#72A0C1_Air superiority blue">Air superiority blue</option>
<option value="#EDEAE0_Alabaster">Alabaster</option>
<option value="#F0F8FF_Alice blue">Alice blue</option>
<option value="#C46210_Alloy orange">Alloy orange</option>
<option value="#EFDECD_Almond">Almond</option>
<option value="#E52B50_Amaranth">Amaranth</option>
<option value="#9F2B68_Amaranth ">Amaranth </option>
<option value="#F19CBB_Amaranth pink">Amaranth pink</option>
<option value="#AB274F_Amaranth purple">Amaranth purple</option>
<option value="#D3212D_Amaranth red">Amaranth red</option>
<option value="#3B7A57_Amazon">Amazon</option>
<option value="#FFBF00_Amber">Amber</option>
<option value="#FF7E00_Amber (SAE/ECE">Amber (SAE/ECE)</option>
<option value="#9966CC_Amethyst">Amethyst</option>
<option value="#3DDC84_Android green">Android green</option>
<option value="#CD9575_Antique brass">Antique brass</option>
<option value="#665D1E_Antique bronze">Antique bronze</option>
<option value="#915C83_Antique fuchsia">Antique fuchsia</option>
<option value="#841B2D_Antique ruby">Antique ruby</option>
<option value="#FAEBD7_Antique white">Antique white</option>
<option value="#008000_Ao (English">Ao (English)</option>
<option value="#8DB600_Apple green">Apple green</option>
<option value="#FBCEB1_Apricot">Apricot</option>
<option value="#00FFFF_Aqua">Aqua</option>
<option value="#7FFFD4_Aquamarine">Aquamarine</option>
<option value="#D0FF14_Arctic lime">Arctic lime</option>
<option value="#4B5320_Army green">Army green</option>
<option value="#8F9779_Artichoke">Artichoke</option>
<option value="#E9D66B_Arylide yellow">Arylide yellow</option>
<option value="#B2BEB5_Ash gray">Ash gray</option>
<option value="#87A96B_Asparagus">Asparagus</option>
<option value="#FF9966_Atomic tangerine">Atomic tangerine</option>
<option value="#A52A2A_Auburn">Auburn</option>
<option value="#FDEE00_Aureolin">Aureolin</option>
<option value="#568203_Avocado">Avocado</option>
<option value="#007FFF_Azure">Azure</option>
<option value="#F0FFFF_Azure (X11/web color">Azure (X11/web color)</option>
<option value="#89CFF0_Baby blue">Baby blue</option>
<option value="#A1CAF1_Baby blue eyes">Baby blue eyes</option>
<option value="#F4C2C2_Baby pink">Baby pink</option>
<option value="#FEFEFA_Baby powder">Baby powder</option>
<option value="#FF91AF_Baker-Miller pink">Baker-Miller pink</option>
<option value="#FAE7B5_Banana Mania">Banana Mania</option>
<option value="#DA1884_Barbie Pink">Barbie Pink</option>
<option value="#7C0A02_Barn red">Barn red</option>
<option value="#848482_Battleship grey">Battleship grey</option>
<option value="#BCD4E6_Beau blue">Beau blue</option>
<option value="#9F8170_Beaver">Beaver</option>
<option value="#F5F5DC_Beige">Beige</option>
<option value="#2E5894_B dazzled blue">B dazzled blue</option>
<option value="#9C2542_Big dip o’ruby">Big dip o’ruby</option>
<option value="#FFE4C4_Bisque">Bisque</option>
<option value="#3D2B1F_Bistre">Bistre</option>
<option value="#967117_Bistre brown">Bistre brown</option>
<option value="#CAE00D_Bitter lemon">Bitter lemon</option>
<option value="#BFFF00_Bitter lime">Bitter lime</option>
<option value="#FE6F5E_Bittersweet">Bittersweet</option>
<option value="#BF4F51_Bittersweet shimmer">Bittersweet shimmer</option>
<option value="#000000_Black">Black</option>
<option value="#3D0C02_Black bean">Black bean</option>
<option value="#1B1811_Black chocolate">Black chocolate</option>
<option value="#3B2F2F_Black coffee">Black coffee</option>
<option value="#54626F_Black coral">Black coral</option>
<option value="#3B3C36_Black olive">Black olive</option>
<option value="#BFAFB2_Black Shadows">Black Shadows</option>
<option value="#FFEBCD_Blanched almond">Blanched almond</option>
<option value="#A57164_Blast-off bronze">Blast-off bronze</option>
<option value="#318CE7_Bleu de France">Bleu de France</option>
<option value="#ACE5EE_Blizzard blue">Blizzard blue</option>
<option value="#FAF0BE_Blond">Blond</option>
<option value="#660000_Blood red">Blood red</option>
<option value="#0000FF_Blue">Blue</option>
<option value="#1F75FE_Blue (Crayola">Blue (Crayola)</option>
<option value="#0093AF_Blue (Munsell">Blue (Munsell)</option>
<option value="#0087BD_Blue (NCS">Blue (NCS)</option>
<option value="#0018A8_Blue (Pantone">Blue (Pantone)</option>
<option value="#333399_Blue (pigment">Blue (pigment)</option>
<option value="#0247FE_Blue (RYB">Blue (RYB)</option>
<option value="#A2A2D0_Blue bell">Blue bell</option>
<option value="#6699CC_Blue-gray">Blue-gray</option>
<option value="#0D98BA_Blue-green">Blue-green</option>
<option value="#064E40_Blue-green (color wheel">Blue-green (color wheel)</option>
<option value="#5DADEC_Blue jeans">Blue jeans</option>
<option value="#126180_Blue sapphire">Blue sapphire</option>
<option value="#8A2BE2_Blue-violet">Blue-violet</option>
<option value="#7366BD_Blue-violet (Crayola">Blue-violet (Crayola)</option>
<option value="#4D1A7F_Blue-violet (color wheel">Blue-violet (color wheel)</option>
<option value="#5072A7_Blue yonder">Blue yonder</option>
<option value="#3C69E7_Bluetiful">Bluetiful</option>
<option value="#DE5D83_Blush">Blush</option>
<option value="#79443B_Bole">Bole</option>
<option value="#E3DAC9_Bone">Bone</option>
<option value="#006A4E_Bottle green">Bottle green</option>
<option value="#87413F_Brandy">Brandy</option>
<option value="#CB4154_Brick red">Brick red</option>
<option value="#66FF00_Bright green">Bright green</option>
<option value="#D891EF_Bright lilac">Bright lilac</option>
<option value="#C32148_Bright maroon">Bright maroon</option>
<option value="#1974D2_Bright navy blue">Bright navy blue</option>
<option value="#FFAA1D_Bright yellow (Crayola">Bright yellow (Crayola)</option>
<option value="#FF55A3_Brilliant rose">Brilliant rose</option>
<option value="#FB607F_Brink pink">Brink pink</option>
<option value="#004225_British racing green">British racing green</option>
<option value="#CD7F32_Bronze">Bronze</option>
<option value="#88540B_Brown">Brown</option>
<option value="#AF6E4D_Brown sugar">Brown sugar</option>
<option value="#1B4D3E_Brunswick green">Brunswick green</option>
<option value="#7BB661_Bud green">Bud green</option>
<option value="#FFC680_Buff">Buff</option>
<option value="#800020_Burgundy">Burgundy</option>
<option value="#DEB887_Burlywood">Burlywood</option>
<option value="#A17A74_Burnished brown">Burnished brown</option>
<option value="#CC5500_Burnt orange">Burnt orange</option>
<option value="#E97451_Burnt sienna">Burnt sienna</option>
<option value="#8A3324_Burnt umber">Burnt umber</option>
<option value="#BD33A4_Byzantine">Byzantine</option>
<option value="#702963_Byzantium">Byzantium</option>
<option value="#536872_Cadet">Cadet</option>
<option value="#5F9EA0_Cadet blue">Cadet blue</option>
<option value="#A9B2C3_Cadet blue (Crayola">Cadet blue (Crayola)</option>
<option value="#91A3B0_Cadet grey">Cadet grey</option>
<option value="#006B3C_Cadmium green">Cadmium green</option>
<option value="#ED872D_Cadmium orange">Cadmium orange</option>
<option value="#E30022_Cadmium red">Cadmium red</option>
<option value="#FFF600_Cadmium yellow">Cadmium yellow</option>
<option value="#A67B5B_Café au lait">Café au lait</option>
<option value="#4B3621_Café noir">Café noir</option>
<option value="#A3C1AD_Cambridge blue">Cambridge blue</option>
<option value="#C19A6B_Camel">Camel</option>
<option value="#EFBBCC_Cameo pink">Cameo pink</option>
<option value="#FFFF99_Canary">Canary</option>
<option value="#FFEF00_Canary yellow">Canary yellow</option>
<option value="#FF0800_Candy apple red">Candy apple red</option>
<option value="#E4717A_Candy pink">Candy pink</option>
<option value="#00BFFF_Capri">Capri</option>
<option value="#592720_Caput mortuum">Caput mortuum</option>
<option value="#C41E3A_Cardinal">Cardinal</option>
<option value="#00CC99_Caribbean green">Caribbean green</option>
<option value="#960018_Carmine">Carmine</option>
<option value="#D70040_Carmine (M&amp;P">Carmine (M&amp;P)</option>
<option value="#FFA6C9_Carnation pink">Carnation pink</option>
<option value="#B31B1B_Carnelian">Carnelian</option>
<option value="#56A0D3_Carolina blue">Carolina blue</option>
<option value="#ED9121_Carrot orange">Carrot orange</option>
<option value="#00563F_Castleton green">Castleton green</option>
<option value="#703642_Catawba">Catawba</option>
<option value="#C95A49_Cedar Chest">Cedar Chest</option>
<option value="#ACE1AF_Celadon">Celadon</option>
<option value="#007BA7_Celadon blue">Celadon blue</option>
<option value="#2F847C_Celadon green">Celadon green</option>
<option value="#B2FFFF_Celeste">Celeste</option>
<option value="#246BCE_Celtic blue">Celtic blue</option>
<option value="#DE3163_Cerise">Cerise</option>
<option value="#007BA7_Cerulean">Cerulean</option>
<option value="#2A52BE_Cerulean blue">Cerulean blue</option>
<option value="#6D9BC3_Cerulean frost">Cerulean frost</option>
<option value="#1DACD6_Cerulean (Crayola">Cerulean (Crayola)</option>
<option value="#007AA5_CG blue">CG blue</option>
<option value="#E03C31_CG red">CG red</option>
<option value="#F7E7CE_Champagne">Champagne</option>
<option value="#F1DDCF_Champagne pink">Champagne pink</option>
<option value="#36454F_Charcoal">Charcoal</option>
<option value="#232B2B_Charleston green">Charleston green</option>
<option value="#E68FAC_Charm pink">Charm pink</option>
<option value="#DFFF00_Chartreuse (traditional">Chartreuse (traditional)</option>
<option value="#7FFF00_Chartreuse (web">Chartreuse (web)</option>
<option value="#FFB7C5_Cherry blossom pink">Cherry blossom pink</option>
<option value="#954535_Chestnut">Chestnut</option>
<option value="#E23D28_Chili red">Chili red</option>
<option value="#DE6FA1_China pink">China pink</option>
<option value="#A8516E_China rose">China rose</option>
<option value="#AA381E_Chinese red">Chinese red</option>
<option value="#856088_Chinese violet">Chinese violet</option>
<option value="#FFB200_Chinese yellow">Chinese yellow</option>
<option value="#7B3F00_Chocolate (traditional">Chocolate (traditional)</option>
<option value="#D2691E_Chocolate (web">Chocolate (web)</option>
<option value="#58111A_Chocolate Cosmos">Chocolate Cosmos</option>
<option value="#FFA700_Chrome yellow">Chrome yellow</option>
<option value="#98817B_Cinereous">Cinereous</option>
<option value="#E34234_Cinnabar">Cinnabar</option>
<option value="#CD607E_Cinnamon Satin">Cinnamon Satin</option>
<option value="#E4D00A_Citrine">Citrine</option>
<option value="#9FA91F_Citron">Citron</option>
<option value="#7F1734_Claret">Claret</option>
<option value="#0047AB_Cobalt blue">Cobalt blue</option>
<option value="#D2691E_Cocoa brown">Cocoa brown</option>
<option value="#6F4E37_Coffee">Coffee</option>
<option value="#B9D9EB_Columbia Blue">Columbia Blue</option>
<option value="#F88379_Congo pink">Congo pink</option>
<option value="#8C92AC_Cool grey">Cool grey</option>
<option value="#B87333_Copper">Copper</option>
<option value="#DA8A67_Copper (Crayola">Copper (Crayola)</option>
<option value="#AD6F69_Copper penny">Copper penny</option>
<option value="#CB6D51_Copper red">Copper red</option>
<option value="#996666_Copper rose">Copper rose</option>
<option value="#FF3800_Coquelicot">Coquelicot</option>
<option value="#FF7F50_Coral">Coral</option>
<option value="#F88379_Coral pink">Coral pink</option>
<option value="#893F45_Cordovan">Cordovan</option>
<option value="#FBEC5D_Corn">Corn</option>
<option value="#B31B1B_Cornell red">Cornell red</option>
<option value="#6495ED_Cornflower blue">Cornflower blue</option>
<option value="#FFF8DC_Cornsilk">Cornsilk</option>
<option value="#2E2D88_Cosmic cobalt">Cosmic cobalt</option>
<option value="#FFF8E7_Cosmic latte">Cosmic latte</option>
<option value="#81613C_Coyote brown">Coyote brown</option>
<option value="#FFBCD9_Cotton candy">Cotton candy</option>
<option value="#FFFDD0_Cream">Cream</option>
<option value="#DC143C_Crimson">Crimson</option>
<option value="#9E1B32_Crimson (UA">Crimson (UA)</option>
<option value="#A7D8DE_Crystal">Crystal</option>
<option value="#F5F5F5_Cultured">Cultured</option>
<option value="#00FFFF_Cyan">Cyan</option>
<option value="#00B7EB_Cyan (process">Cyan (process)</option>
<option value="#58427C_Cyber grape">Cyber grape</option>
<option value="#FFD300_Cyber yellow">Cyber yellow</option>
<option value="#F56FA1_Cyclamen">Cyclamen</option>
<option value="#666699_Dark blue-gray">Dark blue-gray</option>
<option value="#654321_Dark brown">Dark brown</option>
<option value="#5D3954_Dark byzantium">Dark byzantium</option>
<option value="#26428B_Dark cornflower blue">Dark cornflower blue</option>
<option value="#008B8B_Dark cyan">Dark cyan</option>
<option value="#536878_Dark electric blue">Dark electric blue</option>
<option value="#B8860B_Dark goldenrod">Dark goldenrod</option>
<option value="#013220_Dark green">Dark green</option>
<option value="#006400_Dark green (X11">Dark green (X11)</option>
<option value="#1A2421_Dark jungle green">Dark jungle green</option>
<option value="#BDB76B_Dark khaki">Dark khaki</option>
<option value="#483C32_Dark lava">Dark lava</option>
<option value="#534B4F_Dark liver">Dark liver</option>
<option value="#543D37_Dark liver (horses">Dark liver (horses)</option>
<option value="#8B008B_Dark magenta">Dark magenta</option>
<option value="#4A5D23_Dark moss green">Dark moss green</option>
<option value="#556B2F_Dark olive green">Dark olive green</option>
<option value="#FF8C00_Dark orange">Dark orange</option>
<option value="#9932CC_Dark orchid">Dark orchid</option>
<option value="#03C03C_Dark pastel green">Dark pastel green</option>
<option value="#301934_Dark purple">Dark purple</option>
<option value="#8B0000_Dark red">Dark red</option>
<option value="#E9967A_Dark salmon">Dark salmon</option>
<option value="#8FBC8F_Dark sea green">Dark sea green</option>
<option value="#3C1414_Dark sienna">Dark sienna</option>
<option value="#8CBED6_Dark sky blue">Dark sky blue</option>
<option value="#483D8B_Dark slate blue">Dark slate blue</option>
<option value="#2F4F4F_Dark slate gray">Dark slate gray</option>
<option value="#177245_Dark spring green">Dark spring green</option>
<option value="#00CED1_Dark turquoise">Dark turquoise</option>
<option value="#9400D3_Dark violet">Dark violet</option>
<option value="#00703C_Dartmouth green">Dartmouth green</option>
<option value="#555555_Davys grey">Davys grey</option>
<option value="#DA3287_Deep cerise">Deep cerise</option>
<option value="#FAD6A5_Deep champagne">Deep champagne</option>
<option value="#B94E48_Deep chestnut">Deep chestnut</option>
<option value="#004B49_Deep jungle green">Deep jungle green</option>
<option value="#FF1493_Deep pink">Deep pink</option>
<option value="#FF9933_Deep saffron">Deep saffron</option>
<option value="#00BFFF_Deep sky blue">Deep sky blue</option>
<option value="#4A646C_Deep Space Sparkle">Deep Space Sparkle</option>
<option value="#7E5E60_Deep taupe">Deep taupe</option>
<option value="#1560BD_Denim">Denim</option>
<option value="#2243B6_Denim blue">Denim blue</option>
<option value="#C19A6B_Desert">Desert</option>
<option value="#EDC9AF_Desert sand">Desert sand</option>
<option value="#696969_Dim gray">Dim gray</option>
<option value="#1E90FF_Dodger blue">Dodger blue</option>
<option value="#D71868_Dogwood rose">Dogwood rose</option>
<option value="#967117_Drab">Drab</option>
<option value="#00009C_Duke blue">Duke blue</option>
<option value="#EFDFBB_Dutch white">Dutch white</option>
<option value="#E1A95F_Earth yellow">Earth yellow</option>
<option value="#555D50_Ebony">Ebony</option>
<option value="#C2B280_Ecru">Ecru</option>
<option value="#1B1B1B_Eerie black">Eerie black</option>
<option value="#614051_Eggplant">Eggplant</option>
<option value="#F0EAD6_Eggshell">Eggshell</option>
<option value="#1034A6_Egyptian blue">Egyptian blue</option>
<option value="#16161D_Eigengrau">Eigengrau</option>
<option value="#7DF9FF_Electric blue">Electric blue</option>
<option value="#00FF00_Electric green">Electric green</option>
<option value="#6F00FF_Electric indigo">Electric indigo</option>
<option value="#CCFF00_Electric lime">Electric lime</option>
<option value="#BF00FF_Electric purple">Electric purple</option>
<option value="#8F00FF_Electric violet">Electric violet</option>
<option value="#50C878_Emerald">Emerald</option>
<option value="#6C3082_Eminence">Eminence</option>
<option value="#1B4D3E_English green">English green</option>
<option value="#B48395_English lavender">English lavender</option>
<option value="#AB4B52_English red">English red</option>
<option value="#CC474B_English vermillion">English vermillion</option>
<option value="#563C5C_English violet">English violet</option>
<option value="#00FF40_Erin">Erin</option>
<option value="#96C8A2_Eton blue">Eton blue</option>
<option value="#C19A6B_Fallow">Fallow</option>
<option value="#801818_Falu red">Falu red</option>
<option value="#B53389_Fandango">Fandango</option>
<option value="#DE5285_Fandango pink">Fandango pink</option>
<option value="#F400A1_Fashion fuchsia">Fashion fuchsia</option>
<option value="#E5AA70_Fawn">Fawn</option>
<option value="#4D5D53_Feldgrau">Feldgrau</option>
<option value="#4F7942_Fern green">Fern green</option>
<option value="#6C541E_Field drab">Field drab</option>
<option value="#FF5470_Fiery rose">Fiery rose</option>
<option value="#B22222_Firebrick">Firebrick</option>
<option value="#CE2029_Fire engine red">Fire engine red</option>
<option value="#E95C4B_Fire opal">Fire opal</option>
<option value="#E25822_Flame">Flame</option>
<option value="#EEDC82_Flax">Flax</option>
<option value="#A2006D_Flirt">Flirt</option>
<option value="#FFFAF0_Floral white">Floral white</option>
<option value="#15F4EE_Fluorescent blue">Fluorescent blue</option>
<option value="#5FA777_Forest green (Crayola">Forest green (Crayola)</option>
<option value="#014421_Forest green (traditional">Forest green (traditional)</option>
<option value="#228B22_Forest green (web">Forest green (web)</option>
<option value="#A67B5B_French beige">French beige</option>
<option value="#856D4D_French bistre">French bistre</option>
<option value="#0072BB_French blue">French blue</option>
<option value="#FD3F92_French fuchsia">French fuchsia</option>
<option value="#86608E_French lilac">French lilac</option>
<option value="#9EFD38_French lime">French lime</option>
<option value="#D473D4_French mauve">French mauve</option>
<option value="#FD6C9E_French pink">French pink</option>
<option value="#C72C48_French raspberry">French raspberry</option>
<option value="#F64A8A_French rose">French rose</option>
<option value="#77B5FE_French sky blue">French sky blue</option>
<option value="#8806CE_French violet">French violet</option>
<option value="#E936A7_Frostbite">Frostbite</option>
<option value="#FF00FF_Fuchsia">Fuchsia</option>
<option value="#C154C1_Fuchsia (Crayola">Fuchsia (Crayola)</option>
<option value="#CC397B_Fuchsia purple">Fuchsia purple</option>
<option value="#C74375_Fuchsia rose">Fuchsia rose</option>
<option value="#E48400_Fulvous">Fulvous</option>
<option value="#87421_Fuzzy Wuzzy">Fuzzy Wuzzy</option>';
return $colour;
  }
}


?>